### PR TITLE
Updated example so you can edit body as well

### PR DESCRIPTION
**Pull request by Muqito**

### CODE REVIEW

**Comment by Muqito** [comment]
Only error I get now is the "Error while saving translation: Forbidden" when I try to save the translation.

**Comment by Muqito** [comment]
Included yarn.lock so we can avoid issues like: https://github.com/PhraseApp-Blog/gatsby-i18next-example/issues/1

**Comment by theodesp** [comment]
Thank you!

**Comment by Muqito** [comment]
It was fun to help 👍

**Pull request merged**
